# site properties and page defaults
title: Electrogenomics Group
subtitle: 
description: The “Electrogenomics” group was established in 2015 by Professors Munroe, Lambiase and Tinker. This is a collaboration between the William Harvey Research Centre at QMUL and UCL’s Institute of Cardiovascular Science. We joined forces in a broad scale attempt to unravel the electrical and genetic causes of cardiovascular mortality. The team includes world-leading experts in cardiac electrophysiology (Prof. Andy Tinker, QMUL and Prof. Pier Lambiase UCL), genetics (Prof. Patricia Munroe, QMUL) and biomedical engineering (Dr. Michele Orini, UCL), with talented research fellows and PhD students with bioengineering, clinical and genetics training.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: t.kaplan@qmul.ac.uk
  #orcid: 0000-0001-8713-9213
  #google-scholar: ETJoidYAAAAJ
  github: Electrogenomics-Group
  #twitter: Electrogenomics-Group
  #youtube: Electrogenomics-Group

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
